def raise_error(code, error, av_id=None, da_id=None):
    exit()
